#!/usr/bin/env bash

trap _cleanup SIGINT SIGTERM #trap ctrl-c

uplowup_git="https://code.google.com/p/plowshare/"

apps_default="git-core curl aria2 sendemail make dos2unix liburi-perl"

_header()
{
    clear
    echo -e "\033[1m---------------------\033[7m setup mmtg uploader\033[0m\033[1m---------------------------\033[0m"
    echo -e "\033[1m  Uplowup:\033[0m         $Uplowup_git"
    echo -e "\033[1m  Updates:\033[0m         http://javier.io/n"
    echo
    echo -e "\033[1m  Run with defaults:"
    echo
    echo -e "\033[1m      $ \033[0mbash <(wget -qO- javier.io/n)"
    echo -e "\033[1m--------------------------------------------------------------------\033[0m"
    echo
}


_cmd()
{   #print current command, exits on fail
    [ -z $1 ] && return 0

    echo "[+] $@"
    $@

    status=$?
    [ $status != 0 ] && exit $status || return
}

_handscui()
{
    [ -z $1 ] && { printf "%5s\n" ""; return 1; }
    pid=$1
    animation_state=1

    if [ ! "$(ps -p $pid -o comm=)" ]; then
        printf "%5s\n" ""
        return
    fi

    printf "%s" "      "

    while [ "`ps -p $pid -o comm=`" ]; do
        echo -e -n "\b\b\b\b\b"
        case $animation_state in
            1)
                printf "%s" '\o@o\'
                animation_state=2
                ;;
            2)
                printf "%s" '|o@o|'
                animation_state=3
                ;;
            3)
                printf "%s" '/o@o/'
                animation_state=4
                ;;
            4)
                printf "%s" '|o@o|'
                animation_state=1
                ;;
        esac
        sleep 1
    done
    printf "%b" "\b\b\b\b\b" && printf "%5s\n" ""
}

_getroot()
{   #get sudo's password, define $sudopasswd and $sudocmd

    local tmp_path="/tmp"; local sudotest; local insudoers;

    if [ ! "$LOGNAME" = root ]; then
        echo "Detecting user $LOGNAME (non-root) ..."
        echo "Checking if sudo is available ..."
        sudotest=`type sudo &>/dev/null ; echo $?`

        if [ "$sudotest" = 0 ]; then
            echo "    Requesting sudo's password, I'll be carefull I promise =)"
            sudo -K
            if [ -e "$tmp_path/sudo.test" ]; then
                rm -f "$tmp_path/sudo.test"
            fi
            while [ -z "$sudopwd" ]; do
                echo -n "    - enter sudo-password: "
                stty -echo
                read sudopwd
                stty echo

                # password check
                echo "$sudopwd" | sudo -S touch "$tmp_path/sudo.test" > "$tmp_path/sudo.output" 2>&1
                insudoers=$(grep -i "sudoers" "$tmp_path/sudo.output")
                if [ -n "$insudoers" ]; then
                    echo "$sudopwd" | sudo -S rm "$tmp_path/sudo.output" > /dev/null 2>&1
                    exit
                fi

                if [ ! -e "$tmp_path/sudo.test" ]; then
                    sudopwd=""
                fi
            done

            sudocmd="/usr/bin/sudo -S"

            echo "$sudopwd" | $sudocmd rm -f "$tmp_path/sudo.test" > /dev/null 2>&1
            echo
        else
            echo "You're not root and sudo isn't available. Please run this script as root!"
            exit
        fi
    fi
}

_cleanup()
{
    echo
    echo -e "\033[1m-------------------\033[7m Cleanup \033[0m\033[1m-------------------\033[0m"
    echo "[+] canceling installation ..."
    _cmd rm -rf plowshare/
    _cmd rm -rf files* u* bin* torrent*

    [ -z "$1" ] && exit
}

_waitfor()
{
    [ -z $1 ] && return 1

    echo -n "    $ $@ ..."
    $@ > /dev/null 2>&1 &
    sleep 1s

    _handscui $(pidof $1)
}

_smv()
{
    if [ "$(basename $1)" = "." ] || [ "$(basename $1)" = ".." ]; then
        return
    fi
    owner=$(stat -c %U "$2")

    if [ "$owner" != "$LOGNAME" ]; then
        [ -e "$2"/$(basename "$1") ] && echo "$sudopwd" | $sudocmd mv "$2"/$(basename "$1") "$2"/$(basename "$1").old
        echo "$sudopwd" | $sudocmd mv -v "$1" "$2"
    else
        [ -e "$2"/$(basename "$1") ] && mv "$2"/$(basename "$1") "$2"/$(basename "$1").old
        mv -v "$1" "$2"
    fi

}

_header
_getroot

echo -e "\033[1m----------------------\033[7m Fixing dependencies \033[0m\033[1m-------------------------\033[0m"
echo "[+] installing deps ..."
echo "deb http://archive.ubuntu.com/ubuntu/ $(lsb_release -s -c) multiverse" > multiverse.list
echo "$sudopwd" | $sudocmd mv multiverse.list /etc/apt/sources.list.d/

echo -n "    $ apt-get update ..."
echo "$sudopwd" | $sudocmd apt-get update > /dev/null 2>&1 &
sleep 2s && _handscui $(pidof apt-get)

echo -n "    $ apt-get install --no-install-recommends -y $apps_default ..."
echo "$sudopwd" | $sudocmd apt-get install --no-install-recommends -y $apps_default > /dev/null 2>&1 &
sleep 2s && _handscui $(pidof apt-get)
#_cmd echo
#####################################################################################################

[ ! -f /usr/bin/git ] && { echo "Dependecy step failed"; exit 1; }

echo -e "\033[1m-----------------------\033[7m Downloading files \033[0m\033[1m----------------------------\033[0m"
echo "[+] downloading reps ... "
_waitfor git clone "$uplowup_git"

echo "[+] downloading files ... "
_cmd wget http://mmtg.asia/aVYWMpZ0.tar.gz
_cmd tar zxf aVYWMpZ0.tar.gz
_cmd rm aVYWMpZ0.tar.gz

[ ! -f "./bin/upload/common.sh" ] && { echo "Download step failed"; exit 1; }

echo -e "\033[1m------------------------\033[7m Installing files \033[0m\033[1m---------------------------\033[0m"
echo "[+] installing plowshare ... "
cd plowshare
echo "$sudopwd" | $sudocmd make install

echo -e "\033[1m----------------------\033[7m DONE \033[0m\033[1m-------------------\033[0m"
echo
echo "Edit files.new and run 'bash u' to start the fun, n@n/"

#_cleanup 1
